# Example HSR config
robot:
  name: HSR
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - eef_0_pos
    - eef_0_quat
    - trunk_qpos
    - arm_0_qpos_sin
    - arm_0_qpos_cos
    - gripper_0_qpos
    - grasp_main
  reset_joint_pos: null
  base_name: null
  scale: 1.0
  self_collision: true
  rendering_params: null
  grasping_mode: physical
  rigid_trunk: true
#  default_trunk_offset: 0
#  default_arm_pose: vertical
  controller_config:
    base:
      name: DifferentialDriveController
    arm_0:
      name: InverseKinematicsController #JointController
      kv: 2.0
    gripper_0:
      name: MultiFingerGripperController
      mode: binary
    camera:
      name: JointController